CREATE SCHEMA LOL_DATA;

CREATE TABLE LOL_DATA.SERVERS_INFO(
	    SERVER_DEDICATED_COUNTRY VARCHAR(30),
	    SERVER_SHORT_NAME VARCHAR(5),
	    SERVER_FULL_NAME VARCHAR(30),
	    SERVER_ROUTING_VALUE VARCHAR(5),
	    SERVER_REGION VARCHAR(10)
);

CREATE TABLE LOL_DATA.CHALLENGERS_DATA(
	    SUMMONER_PUUID VARCHAR(63),
	    SUMMONER_ID VARCHAR(78),
	    SUMMONER_NAME VARCHAR(16),
	    SERVER_ROUTING_VALUE VARCHAR(5),
	    INGESTION_DATE DATE NOT NULL /*YYYY-MM-DD*/
);

